import React, { useState } from 'react';
import './GeneratedImageViewer.css';

const GeneratedImageViewer = ({ imageData, onClose, onEmailImage, onSaveImage, onCopyImage }) => {
  const [isLoading, setIsLoading] = useState(false);
  const [statusMessage, setStatusMessage] = useState('');

  const handleEmail = async () => {
    setIsLoading(true);
    setStatusMessage('Sending email...');
    try {
      await onEmailImage(imageData);
      setStatusMessage('✅ Email sent!');
      setTimeout(() => setStatusMessage(''), 3000);
    } catch (error) {
      setStatusMessage(`❌ Error: ${error.message}`);
      setTimeout(() => setStatusMessage(''), 5000);
    } finally {
      setIsLoading(false);
    }
  };

  const handleSave = async () => {
    setIsLoading(true);
    setStatusMessage('Saving image...');
    try {
      await onSaveImage(imageData);
      setStatusMessage('✅ Image saved!');
      setTimeout(() => setStatusMessage(''), 3000);
    } catch (error) {
      setStatusMessage(`❌ Error: ${error.message}`);
      setTimeout(() => setStatusMessage(''), 5000);
    } finally {
      setIsLoading(false);
    }
  };

  const handleCopy = async () => {
    setIsLoading(true);
    setStatusMessage('Copying image...');
    try {
      await onCopyImage(imageData);
      setStatusMessage('✅ Image copied!');
      setTimeout(() => setStatusMessage(''), 3000);
    } catch (error) {
      setStatusMessage(`❌ Error: ${error.message}`);
      setTimeout(() => setStatusMessage(''), 5000);
    } finally {
      setIsLoading(false);
    }
  };

  if (!imageData) return null;

  const { base64Image, filename, model, aspectRatio, fileSize } = imageData;
  const imgSrc = `data:image/png;base64,${base64Image}`;

  return (
    <div className="image-viewer-overlay" onClick={onClose}>
      <div className="image-viewer-container" onClick={(e) => e.stopPropagation()}>
        <div className="image-viewer-header">
          <div className="image-info">
            <h3>🎨 Generated Image</h3>
            <p className="image-meta">
              {filename} • {model} • {aspectRatio} • {fileSize}
            </p>
          </div>
          <button className="close-viewer-button" onClick={onClose} title="Close">
            ✕
          </button>
        </div>

        <div className="image-viewer-content">
          <img src={imgSrc} alt="Generated by Nano Banana" className="generated-image" />
        </div>

        <div className="image-viewer-actions">
          <button
            className="action-button email-button"
            onClick={handleEmail}
            disabled={isLoading}
            title="Share via email"
          >
            📧 Email
          </button>
          <button
            className="action-button save-button"
            onClick={handleSave}
            disabled={isLoading}
            title="Save to disk"
          >
            💾 Save
          </button>
          <button
            className="action-button copy-button"
            onClick={handleCopy}
            disabled={isLoading}
            title="Copy to clipboard"
          >
            📋 Copy
          </button>
        </div>

        {statusMessage && (
          <div className="status-message">
            {statusMessage}
          </div>
        )}
      </div>
    </div>
  );
};

export default GeneratedImageViewer;

